### ISSUE TITLE
No answerscripts execution on IRC

### ISSUE THREAD

**Issue by mickcy** [Harvie/libpurple-core-answerscripts#4]
I've tried setting it to reply back as well as running a command, nothing works on IRC for me.
It does work on Yahoo, AIM, MSN and XMPP however.

No errors in .xsession-errors, I have tried a 00-* and a 01-* script, neither works.
Anyone know what I did wrong? // What causes this?

**Comment by Harvie** [comment]
Finaly implemented! :-)
